// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sobulcifgezojgppkibz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnVsY2lmZ2V6b2pncHBraWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDA4NjAsImV4cCI6MjA3MDA3Njg2MH0.B6IWUTy7oTiFOoL07z619oLQXEsb9Cr_MI1eU54d_5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});